apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  namespace: jenkins
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka-server
        image: eureka-server:test
        ports:
        - containerPort: 8761
